[package]
name = "scolor"
version = "0.1.0"
edition = "2021"
description = "Simple ansi colors"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
