[package]
name = "scolor"
version = "4.0.1"
edition = "2021"
description = "Simple ansi colors"
license = "MIT"
keywords = ["color", "ansi", "terminal"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
